const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const SET_FILTER = 'SET_FILTER';
const SET_TODO_TEXT = 'SET_TODO_TEXT';

export default {
    ADD_TODO,TOGGLE_TODO,SET_TODO_TEXT,SET_FILTER
}
